module.exports = {
    AUTO_VIEW_STATUS: 'true',
    AUTO_LIKE_STATUS: 'true',
    AUTO_RECORDING: 'true',
    AUTO_LIKE_EMOJI: ['🌸', '🪴', '💫', '🍂', '🌟','🫀', '👀', '🤖', '🚩', '🥰', '🗿', '💜', '💙', '🌝', '🖤', '💚'],
    PREFIX: '.',
    MAX_RETRIES: 3,
    GROUP_INVITE_LINK: 'https://whatsapp.com/channel/0029VazoKtJ9MF8zrCJVX01w',
    ADMIN_LIST_PATH: './admin.json',
    IMAGE_PATH: 'https://files.catbox.moe/f9gwsx.jpg',
    NEWSLETTER_JID: '120363402507750390@newsletter',
    NEWSLETTER_MESSAGE_ID: '428',
    OTP_EXPIRY: 300000,
    NEWS_JSON_URL: '',
    BOT_NAME: 'ʜᴜsᴇ_ᴛᴇᴄʜ-ᴍᴅ-ᴍɪɴɪ',
    OWNER_NAME: 'ᴍʀ xᴅᴋɪɴɢ',
    OWNER_NUMBER: '263714757857',
    BOT_VERSION: '1.0.2',
    BOT_FOOTER: '> ᴘᴏᴡᴇʀᴇᴅ ʙʏ ʜᴜsᴇ_ᴛᴇᴄʜ-ᴍᴅ',
    CHANNEL_LINK: 'https://whatsapp.com/channel/0029VazoKtJ9MF8zrCJVX01w',
};
